spring:
  application:
    name: grinder
  datasource:
    driver-class-name: ENC(qUd7z0u9cv/ufdS5y5M9mH5408IjRv1w1nmv9z18W0wjUFzISZIr7Q==)
    url: ENC(TXNeJHKB6555E6BKWt0JtfQnYROuZs43+fFC9eyJji58FEpNL6K44GQVMmjJYJEZkGU1lR6cAspmBuT7RWa/I75lCm6e7KWJHrUTXB44xRR/hcqfuBwHtUjKpl/XfthYK5Zs8z/CxKsfeNrpZMoNHAgYM2O9rkYaVif7KBpIDrB+DgOAt+2VEA==)
    username: ENC(x+cM3eM5dXMMvtjcaS2lo/0mogj1SnUw)
    password: ENC(75GW/0QEsaOTKReqHGOxt0BJ3pd7V7XU)
    hikari:
      connection-timeout: 10000
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ENC(cPpWmy1bRHSmNLIVa/07KhxVyMtOvf9clNBRNNetshk=)
            client-secret: ENC(fvYj+WAbNCPveV0wRRZvMe6pskohKeLB)
            redirect-uri: ENC(lWQY1dlOSYaPMpAawj/mRkdshIjQTYVjdV9Dr0dQAQsMDnRPahVfao8Gc9rEz2HvbRWcqIRWU1s=)
            authorization-grant-type: authorization_code
            provider: naver
            scope:
              - name
              - email
          google:
            client-name: google
            client-id: ENC(ZbYfiO0SRwaewrDp9VCZAqpsyxzfaU7tJiGSrn0veKV/3X+rmrnZv4QQrVcnigfCsii+6sQVdOsKeUaNpJs16gJuWpvTKZ+ELZxii14KMhPsm483xF/YnA==)
            client-secret: ENC(i6e2a6JLniaAG/qgjKPYSsDk9AqxJAtQfWVHlhzGLxTFG27+8LsJ5ucij/imNm66)
            redirect-uri: ENC(OcOB6ZXVKfjLHYtuA1fIwRLU7eDZbyzJQhuRdFJwZQabi724d5v0PsVTlscEJvKXEH7Xnsjwn5w=)
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            client-id: ENC(NU8nItxNprfX+TRnNjKLstiSYi1w9Zw2LmSSGNP78wvvdADFhaRNu4UcyPWT8d1Y)
            client-secret: ENC(OEU1xmCOg1m4550qaUrvFMH/WBDLfp4FqBo4xFPJuSWQ1fXMJocBoJi/SMOSgizy)
            redirect-uri: ENC(B9549fFiFR23XzUzplLYUt6SUgE4e+zod87xFRGzXOQRhgumWU3gtQJXmzn89qr6fioiWZ0Y/Xw=)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            provider: kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: ENC(TeVq+bFrL+WbILoraSLsVsutbyzGP8e0oVayHhnorHysM5iY66ZfnGKQcaSX4saNQ/3LFxZ6etA=)
            token-uri: ENC(aeRHoputB2DeXiCnm/8M9R9pP7jIfGAh2v1HbF25zL2jmQ19zIZtJgwl35Scqpdr)
            user-info-uri: ENC(szyEnD/rOuJH5YmWZWyjcb4Cfqw9bbuTjJ+/zIVSDzx3U+4rz5zkFiG2tkyoUzZl)
            user-name-attribute: response
          kakao:
            authorization-uri: ENC(cLZXUfFeBu+/6uF9rERJix9wPSIlV94YEXalNhfySLaa0iqJx9+tPDrF/MH20WpV)
            token-uri: ENC(XI+aj4zB8wNryuj+DCzqiLVoeTY4moU4ox5hjChQpwr2kwNAUJ615ShM4EGjXU4e)
            user-info-uri: ENC(T9IZi3zqyK8jDbUy8r0BN0Tp4buz+8xHoqP78YUxAZRGMVbJ54KY/ruuxRTBbbUs)
            user-name-attribute: id

server:
  tomcat:
    threads:
      min-spare: 2
      max: 5

logging:
  level:
    org:
      springframework:
        info:
        security: trace
    zercok: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

jasypt:
  encryptor:
    bean: jasyptStringEncryptor